version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "24004:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://tubik-corp.ru:24003
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "24003:5000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    environment:
      - ADMIN_PASSWORD_HASH=your_hashed_password_here
