# docker-compose.yml
version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "24004:24004"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    user: "node"
    environment:
      - SERVER_PORT=24004
      - API_URL=http://tubik-corp.ru:24003

  backend:
    build: ./backend
    ports:
      - "24003:5000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      
# volumes:
#   frontend_node_modules:
